keys:
  - &admin age19aesmaqmck97rh3hgswmwas4uflmd4kfx47v5gg57yj58jswccuq0x0vyg
  - &mangrove age13m2jqa3ddjkffjqu82gk40u42kqdypletd605ax7u3krpfx4sfhq9wq853

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin
          - *mangrove
