import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { SCHEMA_VERSION, validateCatalog } from './catalog-schema.mjs'
import { mergeCatalog } from './merge-catalog.mjs'
import { importKubeJs } from './sources/kubejs.mjs'
import { importKubeJsExport } from './sources/kubejs-export.mjs'
import { importJsonCatalog } from './sources/json.mjs'

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const args = process.argv.slice(2)
const option = (name) => {
  const index = args.indexOf(name)
  return index < 0 ? null : args[index + 1]
}
const options = (name) =>
  args.flatMap((value, index) => (value === name && args[index + 1] ? [args[index + 1]] : []))
const sourceRoot = option('--source-root')
const packMode = option('--pack-mode') ?? 'default'
if (!['default', 'hard', 'abydos'].includes(packMode)) throw new Error('Unsupported pack mode')
if (!sourceRoot) {
  throw new Error(
    'Usage: npm run catalog:build -- --source-root /path/to/Star-Technology [--kubejs-export /path/to/local/kubejs/export] [--json /path/to/catalog.json]',
  )
}

const sourceId = 'star-technology-kubejs'
const commit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: sourceRoot, encoding: 'utf8' }).trim()
const sourceDate = execFileSync('git', ['show', '-s', '--format=%cI', 'HEAD'], {
  cwd: sourceRoot,
  encoding: 'utf8',
}).trim()
const manifest = JSON.parse(await readFile(path.join(sourceRoot, 'compile_data', 'manifest.json'), 'utf8'))
const packVersion = option('--pack-version') ?? manifest.version
if (!packVersion || packVersion === 'COMPILED')
  throw new Error('Pass --pack-version for a source tag with a compiled manifest placeholder')
const imported = await importKubeJs(sourceRoot, sourceId, packMode)
const runtimeRoot = option('--kubejs-export')
const runtime = runtimeRoot ? await importKubeJsExport(runtimeRoot) : null
if (runtime?.diagnostics.length) {
  throw new Error(`Runtime export contains ${runtime.diagnostics.length} unreadable recipe files`)
}
const sourceRecipes = runtime
  ? imported.recipes.map((recipe) => ({ ...recipe, availability: 'source-declaration' }))
  : imported.recipes
const usedTags = new Set(
  [...(runtime?.recipes ?? []), ...sourceRecipes].flatMap((recipe) =>
    recipe.inputs
      .filter((stack) => stack.id.startsWith('#'))
      .map((stack) => `${stack.unit}|${stack.id.slice(1)}`),
  ),
)
const tags = runtime
  ? Object.fromEntries(
      Object.entries(runtime.tags).filter(([key, members]) => usedTags.has(key) && members.length > 1),
    )
  : {}
const contributions = [
  {
    sources: [
      {
        id: sourceId,
        name: 'Star Technology KubeJS',
        kind: 'kubejs-source',
        url: 'https://github.com/StarT-Dev-Team/Star-Technology',
        commit,
        license: 'MIT',
        scope: `Pack-authored server-side KubeJS scripts for ${packMode} mode; excludes recipes generated by installed mods at runtime.`,
        recipeCount: sourceRecipes.length,
        fileCount: imported.fileCount,
      },
    ],
    recipes: sourceRecipes,
    diagnostics: imported.diagnostics,
    fileCount: imported.fileCount,
  },
]
if (runtime) {
  contributions.push({
    sources: [
      {
        id: 'star-technology-runtime',
        name: 'Star Technology in-game KubeJS export',
        kind: 'kubejs-export',
        url: '',
        commit: '',
        license: 'Local export',
        scope: `Final registered recipes exported from the ${packVersion} ${packMode} instance after recipe loading and KubeJS changes.`,
        recipeCount: runtime.recipes.length,
        fileCount: runtime.fileCount,
      },
    ],
    recipes: runtime.recipes.map((recipe) => ({ ...recipe, availability: 'registered' })),
    tags,
    diagnostics: runtime.diagnostics,
    fileCount: runtime.fileCount,
  })
}
for (const jsonPath of options('--json')) {
  const extra = await importJsonCatalog(jsonPath)
  if (extra.packVersion !== packVersion || extra.packMode !== packMode)
    throw new Error('Additional catalog must match pack version and mode')
  contributions.push(extra)
}
const catalog = mergeCatalog({ generatedAt: sourceDate, packVersion, packMode }, contributions)
if (runtime) catalog.rawCatalog = 'catalog-raw.json'
validateCatalog(catalog)
const output = option('--output') ?? path.join(appRoot, 'public', 'catalog.json')
await mkdir(path.dirname(output), { recursive: true })
await writeFile(output, JSON.stringify(catalog))
if (runtime) {
  const rawOutput = option('--raw-output') ?? path.join(path.dirname(output), 'catalog-raw.json')
  await writeFile(
    rawOutput,
    JSON.stringify({ schemaVersion: SCHEMA_VERSION, packVersion, packMode, recipes: runtime.rawRecipes }),
  )
}
const complete = catalog.recipes.filter((recipe) => recipe.unresolved.length === 0).length
console.log(`Wrote ${catalog.recipes.length} recipes from ${catalog.fileCount} source files to ${output}`)
console.log(
  `${complete} fully parsed; ${catalog.recipes.length - complete} have unresolved fields; ${catalog.diagnostics.length} file diagnostics`,
)
