{
  imports = [
    ./ports.nix
    ./base.nix
    ./networking.nix
    ./authentik
    ./media.nix
    ./arr.nix
    ./monitoring.nix
    ./copyparty.nix
    ./romm.nix
    ./pelican.nix
    ./gaming-vm.nix
    ./mealie.nix
    ./actual.nix
    ./backup.nix
    ./overseerr.nix
    ./frigate.nix
  ];
}
