{
  imports = [
    ./ports.nix
    ./base.nix
    ./networking.nix
    ./authentik
    ./media.nix
    ./arr.nix
    ./monitoring.nix
    ./copyparty.nix
    ./docker.nix
    ./romm.nix
    ./pelican.nix
    ./gaming-vm.nix
    ./vm-console.nix
    ./mealie.nix
    ./actual.nix
    ./wealthfolio.nix
    ./tilt.nix
    ./coder
    ./github-runners.nix
    ./backup.nix
    ./overseerr.nix
    ./frigate.nix
    ./home-assistant.nix
    ./security.nix
  ];
}
